// IELTS Academic Word Bank — 200 high-frequency words organized by topic
// Each word includes: definition, pronunciation, IELTS example sentence, synonyms, topic, band level

export interface WordEntry {
  word: string
  definition: string
  pronunciation: string
  exampleSentence: string
  synonyms: string[]
  topic: string
  band: number
}

export const WORD_BANK: WordEntry[] = [
  // === ENVIRONMENT ===
  {
    word: "sustainable",
    definition: "able to be maintained at a certain rate or level without depleting natural resources",
    pronunciation: "/səˈsteɪnəbl/",
    exampleSentence: "Governments must invest in sustainable energy sources to combat climate change.",
    synonyms: ["eco-friendly", "viable", "renewable"],
    topic: "Environment",
    band: 6,
  },
  {
    word: "biodiversity",
    definition: "the variety of plant and animal life in the world or a particular habitat",
    pronunciation: "/ˌbaɪoʊdaɪˈvɜːrsəti/",
    exampleSentence: "Deforestation poses a significant threat to the biodiversity of tropical rainforests.",
    synonyms: ["ecological variety", "species richness", "biological diversity"],
    topic: "Environment",
    band: 7,
  },
  {
    word: "mitigation",
    definition: "the action of reducing the severity or seriousness of something",
    pronunciation: "/ˌmɪtɪˈɡeɪʃn/",
    exampleSentence: "Effective mitigation strategies are essential to limit the impact of global warming.",
    synonyms: ["reduction", "alleviation", "lessening"],
    topic: "Environment",
    band: 8,
  },
  {
    word: "emission",
    definition: "the production and discharge of something, especially gas or radiation",
    pronunciation: "/ɪˈmɪʃn/",
    exampleSentence: "Carbon emissions from vehicles are a major contributor to air pollution in urban areas.",
    synonyms: ["discharge", "release", "output"],
    topic: "Environment",
    band: 6,
  },
  {
    word: "deforestation",
    definition: "the action of clearing a wide area of trees",
    pronunciation: "/ˌdiːˌfɒrɪˈsteɪʃn/",
    exampleSentence: "Rapid deforestation in Southeast Asia has led to widespread habitat destruction.",
    synonyms: ["land clearing", "tree felling", "forest destruction"],
    topic: "Environment",
    band: 6,
  },
  {
    word: "renewable",
    definition: "not depleted when used; capable of being replenished naturally",
    pronunciation: "/rɪˈnjuːəbl/",
    exampleSentence: "Solar and wind power are the most cost-effective renewable energy sources available today.",
    synonyms: ["sustainable", "inexhaustible", "perpetual"],
    topic: "Environment",
    band: 6,
  },
  {
    word: "catastrophic",
    definition: "involving or causing sudden great damage or suffering",
    pronunciation: "/ˌkætəˈstrɒfɪk/",
    exampleSentence: "Scientists warn of catastrophic consequences if global temperatures rise by more than 2°C.",
    synonyms: ["devastating", "disastrous", "calamitous"],
    topic: "Environment",
    band: 7,
  },
  {
    word: "ecosystem",
    definition: "a biological community of interacting organisms and their physical environment",
    pronunciation: "/ˈiːkəʊˌsɪstəm/",
    exampleSentence: "The destruction of coral reefs threatens the entire marine ecosystem.",
    synonyms: ["habitat", "biosphere", "ecological system"],
    topic: "Environment",
    band: 7,
  },
  {
    word: "contamination",
    definition: "the action or state of making or being made impure by polluting or poisoning",
    pronunciation: "/kənˌtæmɪˈneɪʃn/",
    exampleSentence: "Industrial waste has led to severe contamination of local water supplies.",
    synonyms: ["pollution", "impurity", "adulteration"],
    topic: "Environment",
    band: 7,
  },
  {
    word: "conservation",
    definition: "the protection of animals, plants, and natural resources",
    pronunciation: "/ˌkɒnsəˈveɪʃn/",
    exampleSentence: "Wildlife conservation programmes have helped endangered species recover their numbers.",
    synonyms: ["preservation", "protection", "safeguarding"],
    topic: "Environment",
    band: 6,
  },

  // === TECHNOLOGY ===
  {
    word: "automation",
    definition: "the use of technology to perform tasks with minimal human assistance",
    pronunciation: "/ˌɔːtəˈmeɪʃn/",
    exampleSentence: "The automation of manufacturing processes has drastically reduced production costs.",
    synonyms: ["mechanisation", "computerisation", "robotics"],
    topic: "Technology",
    band: 7,
  },
  {
    word: "innovation",
    definition: "the introduction of new ideas, methods, or technologies",
    pronunciation: "/ˌɪnəˈveɪʃn/",
    exampleSentence: "Technological innovation in the healthcare sector has improved patient outcomes significantly.",
    synonyms: ["advancement", "breakthrough", "progress"],
    topic: "Technology",
    band: 6,
  },
  {
    word: "algorithm",
    definition: "a process or set of rules followed in calculations or problem-solving by a computer",
    pronunciation: "/ˈælɡərɪðəm/",
    exampleSentence: "Social media platforms use complex algorithms to personalise users' content feeds.",
    synonyms: ["procedure", "formula", "protocol"],
    topic: "Technology",
    band: 8,
  },
  {
    word: "surveillance",
    definition: "close observation, especially of a suspected spy or criminal, or monitoring by camera",
    pronunciation: "/səˈveɪləns/",
    exampleSentence: "Mass surveillance systems raise serious concerns about individual privacy rights.",
    synonyms: ["monitoring", "observation", "tracking"],
    topic: "Technology",
    band: 7,
  },
  {
    word: "proliferation",
    definition: "rapid increase in the number or amount of something",
    pronunciation: "/prəˌlɪfəˈreɪʃn/",
    exampleSentence: "The proliferation of smartphones has fundamentally transformed how people communicate.",
    synonyms: ["spread", "expansion", "multiplication"],
    topic: "Technology",
    band: 8,
  },
  {
    word: "artificial intelligence",
    definition: "the simulation of human intelligence processes by computer systems",
    pronunciation: "/ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns/",
    exampleSentence: "Artificial intelligence is increasingly being used to diagnose diseases with greater accuracy than doctors.",
    synonyms: ["machine learning", "AI", "computational intelligence"],
    topic: "Technology",
    band: 7,
  },
  {
    word: "obsolete",
    definition: "no longer produced or used; out of date",
    pronunciation: "/ˈɒbsəliːt/",
    exampleSentence: "Many traditional jobs are becoming obsolete as a result of rapid technological advancement.",
    synonyms: ["outdated", "outmoded", "superseded"],
    topic: "Technology",
    band: 7,
  },
  {
    word: "cybersecurity",
    definition: "the practice of protecting computers and networks from digital attacks",
    pronunciation: "/ˈsaɪbəsɪˌkjʊərɪti/",
    exampleSentence: "Companies are investing heavily in cybersecurity to protect sensitive customer data.",
    synonyms: ["data protection", "network security", "information security"],
    topic: "Technology",
    band: 7,
  },

  // === HEALTH ===
  {
    word: "sedentary",
    definition: "tending to spend much time seated; characterised by little physical exercise",
    pronunciation: "/ˈsɛdntri/",
    exampleSentence: "A sedentary lifestyle is one of the leading risk factors for obesity and cardiovascular disease.",
    synonyms: ["inactive", "stationary", "desk-bound"],
    topic: "Health",
    band: 8,
  },
  {
    word: "prevalence",
    definition: "the fact or condition of being widespread at a particular time",
    pronunciation: "/ˈprɛvələns/",
    exampleSentence: "The prevalence of mental health disorders among young people has increased dramatically.",
    synonyms: ["frequency", "commonness", "incidence"],
    topic: "Health",
    band: 7,
  },
  {
    word: "obesity",
    definition: "the condition of being grossly overweight or obese",
    pronunciation: "/oʊˈbiːsɪti/",
    exampleSentence: "Childhood obesity has become a global health crisis, particularly in developed nations.",
    synonyms: ["overweight", "corpulence", "excessive weight"],
    topic: "Health",
    band: 6,
  },
  {
    word: "deteriorate",
    definition: "become progressively worse",
    pronunciation: "/dɪˈtɪərɪəreɪt/",
    exampleSentence: "Without proper treatment, a patient's condition can deteriorate rapidly.",
    synonyms: ["worsen", "decline", "degrade"],
    topic: "Health",
    band: 7,
  },
  {
    word: "intervention",
    definition: "action taken to improve a situation, especially a medical procedure",
    pronunciation: "/ˌɪntəˈvɛnʃn/",
    exampleSentence: "Early medical intervention can significantly improve recovery rates for stroke patients.",
    synonyms: ["treatment", "procedure", "involvement"],
    topic: "Health",
    band: 7,
  },
  {
    word: "epidemic",
    definition: "a widespread occurrence of an infectious disease in a community",
    pronunciation: "/ˌɛpɪˈdɛmɪk/",
    exampleSentence: "The obesity epidemic in Western countries is placing enormous strain on healthcare systems.",
    synonyms: ["outbreak", "pandemic", "plague"],
    topic: "Health",
    band: 7,
  },
  {
    word: "resilience",
    definition: "the capacity to recover quickly from difficulties; toughness",
    pronunciation: "/rɪˈzɪliəns/",
    exampleSentence: "Building emotional resilience in young people is essential for their long-term mental wellbeing.",
    synonyms: ["toughness", "adaptability", "hardiness"],
    topic: "Health",
    band: 7,
  },
  {
    word: "malnutrition",
    definition: "lack of proper nutrition, caused by insufficient or unbalanced diet",
    pronunciation: "/ˌmælnjuːˈtrɪʃn/",
    exampleSentence: "Malnutrition affects millions of children in developing countries, stunting both physical and cognitive growth.",
    synonyms: ["undernutrition", "nutritional deficiency", "malnourishment"],
    topic: "Health",
    band: 7,
  },

  // === EDUCATION ===
  {
    word: "curriculum",
    definition: "the subjects comprising a course of study in a school or university",
    pronunciation: "/kəˈrɪkjʊləm/",
    exampleSentence: "Critics argue that the national curriculum fails to develop critical thinking skills.",
    synonyms: ["syllabus", "programme of study", "coursework"],
    topic: "Education",
    band: 6,
  },
  {
    word: "pedagogical",
    definition: "relating to teaching methods or pedagogy",
    pronunciation: "/ˌpɛdəˈɡɒdʒɪkl/",
    exampleSentence: "Innovative pedagogical approaches, such as project-based learning, engage students more effectively.",
    synonyms: ["educational", "instructional", "didactic"],
    topic: "Education",
    band: 9,
  },
  {
    word: "compulsory",
    definition: "required by law or a rule; obligatory",
    pronunciation: "/kəmˈpʌlsəri/",
    exampleSentence: "In most countries, education is compulsory up to the age of sixteen.",
    synonyms: ["mandatory", "obligatory", "required"],
    topic: "Education",
    band: 6,
  },
  {
    word: "literacy",
    definition: "the ability to read and write; competence or knowledge in a specified area",
    pronunciation: "/ˈlɪtərəsi/",
    exampleSentence: "Digital literacy is now considered as important as traditional reading and writing skills.",
    synonyms: ["proficiency", "competence", "ability"],
    topic: "Education",
    band: 6,
  },
  {
    word: "vocational",
    definition: "relating to an occupation or employment, especially a skilled trade",
    pronunciation: "/vəˈkeɪʃənl/",
    exampleSentence: "There is growing demand for vocational training programmes that lead directly to employment.",
    synonyms: ["occupational", "professional", "trade"],
    topic: "Education",
    band: 7,
  },
  {
    word: "academic",
    definition: "relating to education and scholarship, especially at higher levels",
    pronunciation: "/ˌækəˈdɛmɪk/",
    exampleSentence: "Academic performance alone does not prepare students for the challenges of the modern workplace.",
    synonyms: ["scholarly", "educational", "intellectual"],
    topic: "Education",
    band: 6,
  },
  {
    word: "disparity",
    definition: "a great difference in inequality, especially in a social context",
    pronunciation: "/dɪˈspærɪti/",
    exampleSentence: "The disparity in educational quality between rural and urban schools remains a serious concern.",
    synonyms: ["inequality", "gap", "imbalance"],
    topic: "Education",
    band: 8,
  },

  // === SOCIETY ===
  {
    word: "inequality",
    definition: "difference in size, degree, circumstances, or social standing",
    pronunciation: "/ˌɪnɪˈkwɒlɪti/",
    exampleSentence: "Growing economic inequality is one of the most pressing social issues of our time.",
    synonyms: ["disparity", "imbalance", "unfairness"],
    topic: "Society",
    band: 6,
  },
  {
    word: "demographic",
    definition: "relating to the structure of populations, especially human populations",
    pronunciation: "/ˌdɛməˈɡræfɪk/",
    exampleSentence: "Many developed countries face a demographic challenge as their populations age rapidly.",
    synonyms: ["population", "statistical", "sociological"],
    topic: "Society",
    band: 7,
  },
  {
    word: "multicultural",
    definition: "relating to or containing several cultural or ethnic groups",
    pronunciation: "/ˌmʌltiˈkʌltʃərəl/",
    exampleSentence: "A multicultural society benefits from the diverse perspectives and skills of its members.",
    synonyms: ["diverse", "pluralistic", "cosmopolitan"],
    topic: "Society",
    band: 6,
  },
  {
    word: "cohesion",
    definition: "the action or fact of forming a united whole; togetherness",
    pronunciation: "/kəʊˈhiːʒn/",
    exampleSentence: "Community cohesion is vital for maintaining peace and order in diverse urban areas.",
    synonyms: ["unity", "solidarity", "harmony"],
    topic: "Society",
    band: 8,
  },
  {
    word: "marginalise",
    definition: "to treat a person or group as insignificant or peripheral",
    pronunciation: "/ˈmɑːdʒɪnəlaɪz/",
    exampleSentence: "Certain immigrant communities risk being marginalised if language support is not provided.",
    synonyms: ["exclude", "alienate", "isolate"],
    topic: "Society",
    band: 8,
  },
  {
    word: "urbanisation",
    definition: "the process by which towns and cities grow larger as more people move to live in them",
    pronunciation: "/ˌɜːbənaɪˈzeɪʃn/",
    exampleSentence: "Rapid urbanisation in developing countries has led to the growth of informal slum settlements.",
    synonyms: ["urban growth", "city expansion", "metropolitan development"],
    topic: "Society",
    band: 6,
  },
  {
    word: "welfare",
    definition: "the health, happiness, and fortunes of a person or group; financial assistance from the state",
    pronunciation: "/ˈwɛlfeər/",
    exampleSentence: "Cuts to the welfare state have disproportionately affected low-income families.",
    synonyms: ["wellbeing", "social support", "benefit"],
    topic: "Society",
    band: 6,
  },
  {
    word: "discrimination",
    definition: "the unjust treatment of different categories of people",
    pronunciation: "/dɪˌskrɪmɪˈneɪʃn/",
    exampleSentence: "Workplace discrimination based on gender or ethnicity remains a significant barrier to equality.",
    synonyms: ["prejudice", "bias", "inequity"],
    topic: "Society",
    band: 6,
  },

  // === ECONOMY ===
  {
    word: "globalisation",
    definition: "the process by which businesses and organisations develop international influence",
    pronunciation: "/ˌɡloʊbəlaɪˈzeɪʃn/",
    exampleSentence: "Economic globalisation has created unprecedented opportunities for trade but also increased inequality.",
    synonyms: ["internationalisation", "worldwide integration", "global expansion"],
    topic: "Economy",
    band: 6,
  },
  {
    word: "recession",
    definition: "a period of temporary economic decline during which trade and industrial activity are reduced",
    pronunciation: "/rɪˈsɛʃn/",
    exampleSentence: "The 2008 financial recession had devastating effects on employment rates worldwide.",
    synonyms: ["downturn", "slump", "contraction"],
    topic: "Economy",
    band: 6,
  },
  {
    word: "infrastructure",
    definition: "the basic physical and organisational structures needed for a society or enterprise",
    pronunciation: "/ˈɪnfrəˌstrʌktʃər/",
    exampleSentence: "Investing in transport infrastructure is crucial for stimulating regional economic growth.",
    synonyms: ["framework", "foundation", "facilities"],
    topic: "Economy",
    band: 7,
  },
  {
    word: "entrepreneurship",
    definition: "the activity of setting up a business or businesses, taking on financial risks",
    pronunciation: "/ˌɒntrəprəˈnɜːʃɪp/",
    exampleSentence: "Entrepreneurship is widely regarded as a key driver of innovation and job creation.",
    synonyms: ["business initiative", "enterprise", "venture"],
    topic: "Economy",
    band: 7,
  },
  {
    word: "subsidy",
    definition: "a sum of money granted by the state to support an industry or keep prices low",
    pronunciation: "/ˈsʌbsɪdi/",
    exampleSentence: "Government subsidies for renewable energy have helped reduce costs in the sector.",
    synonyms: ["grant", "allowance", "financial support"],
    topic: "Economy",
    band: 7,
  },
  {
    word: "fiscal",
    definition: "relating to government revenue, especially taxes",
    pronunciation: "/ˈfɪskl/",
    exampleSentence: "Stringent fiscal policies are necessary to reduce a country's national debt.",
    synonyms: ["financial", "budgetary", "economic"],
    topic: "Economy",
    band: 8,
  },
  {
    word: "austerity",
    definition: "difficult economic conditions created by government measures to reduce a budget deficit",
    pronunciation: "/ɒˈstɛrɪti/",
    exampleSentence: "Years of austerity measures have severely reduced public services in many European countries.",
    synonyms: ["economic stringency", "belt-tightening", "financial cutbacks"],
    topic: "Economy",
    band: 8,
  },
  {
    word: "consumption",
    definition: "the using up of a resource, or the purchase and use of goods and services",
    pronunciation: "/kənˈsʌmpʃn/",
    exampleSentence: "Reducing energy consumption in homes is one of the most effective ways to lower carbon emissions.",
    synonyms: ["use", "expenditure", "utilisation"],
    topic: "Economy",
    band: 6,
  },

  // === SCIENCE ===
  {
    word: "empirical",
    definition: "based on observation or experience rather than theory",
    pronunciation: "/ɪmˈpɪrɪkl/",
    exampleSentence: "Scientific claims should always be supported by empirical evidence from controlled experiments.",
    synonyms: ["observational", "evidence-based", "experimental"],
    topic: "Science",
    band: 8,
  },
  {
    word: "hypothesis",
    definition: "a proposed explanation for a phenomenon, to be tested through research",
    pronunciation: "/haɪˈpɒθɪsɪs/",
    exampleSentence: "Researchers developed a hypothesis linking stress levels to cardiovascular disease.",
    synonyms: ["theory", "assumption", "proposition"],
    topic: "Science",
    band: 7,
  },
  {
    word: "genomics",
    definition: "the branch of molecular biology concerned with the study of genomes",
    pronunciation: "/dʒɪˈnoʊmɪks/",
    exampleSentence: "Advances in genomics have opened new possibilities for personalised medicine.",
    synonyms: ["genetic science", "gene mapping", "molecular biology"],
    topic: "Science",
    band: 9,
  },
  {
    word: "interdisciplinary",
    definition: "relating to more than one branch of knowledge",
    pronunciation: "/ˌɪntədɪˈsɪplɪnri/",
    exampleSentence: "Solving climate change requires interdisciplinary collaboration across science, economics, and policy.",
    synonyms: ["cross-disciplinary", "multidisciplinary", "collaborative"],
    topic: "Science",
    band: 8,
  },
  {
    word: "empirical evidence",
    definition: "information acquired by observation or experimentation",
    pronunciation: "/ɪmˈpɪrɪkl ˈɛvɪdəns/",
    exampleSentence: "Scientists rely on empirical evidence gathered through rigorous experiments to validate their theories.",
    synonyms: ["observational data", "experimental proof", "factual basis"],
    topic: "Science",
    band: 7,
  },

  // === CULTURE ===
  {
    word: "heritage",
    definition: "valued objects and qualities such as cultural traditions passed down from previous generations",
    pronunciation: "/ˈhɛrɪtɪdʒ/",
    exampleSentence: "UNESCO works to protect cultural heritage sites from the threats of modernisation and conflict.",
    synonyms: ["tradition", "legacy", "history"],
    topic: "Culture",
    band: 6,
  },
  {
    word: "assimilation",
    definition: "the process of taking in and fully understanding information; integration into a group",
    pronunciation: "/əˌsɪmɪˈleɪʃn/",
    exampleSentence: "The assimilation of immigrants into mainstream society is a complex and lengthy process.",
    synonyms: ["integration", "absorption", "acculturation"],
    topic: "Culture",
    band: 8,
  },
  {
    word: "indigenous",
    definition: "originating or occurring naturally in a particular place; native",
    pronunciation: "/ɪnˈdɪdʒɪnəs/",
    exampleSentence: "The rights of indigenous communities must be protected when developing natural resources.",
    synonyms: ["native", "aboriginal", "original"],
    topic: "Culture",
    band: 7,
  },
  {
    word: "cosmopolitan",
    definition: "familiar with and at ease in many different countries and cultures",
    pronunciation: "/ˌkɒzməˈpɒlɪtən/",
    exampleSentence: "London is one of the most cosmopolitan cities in the world, home to people from over 200 nationalities.",
    synonyms: ["multicultural", "international", "worldly"],
    topic: "Culture",
    band: 7,
  },

  // === MEDIA & COMMUNICATION ===
  {
    word: "censorship",
    definition: "the suppression of speech, public communication, or information",
    pronunciation: "/ˈsɛnsəʃɪp/",
    exampleSentence: "Internet censorship in some countries restricts citizens' access to information.",
    synonyms: ["suppression", "restriction", "filtering"],
    topic: "Media",
    band: 7,
  },
  {
    word: "propaganda",
    definition: "information, especially of a biased nature, used to promote a political cause",
    pronunciation: "/ˌprɒpəˈɡændə/",
    exampleSentence: "State-controlled media often disseminates propaganda to shape public opinion.",
    synonyms: ["disinformation", "spin", "indoctrination"],
    topic: "Media",
    band: 7,
  },
  {
    word: "misinformation",
    definition: "false or inaccurate information, especially spread intentionally",
    pronunciation: "/ˌmɪsɪnfəˈmeɪʃn/",
    exampleSentence: "The rapid spread of misinformation on social media poses a serious threat to public health.",
    synonyms: ["disinformation", "false news", "inaccuracy"],
    topic: "Media",
    band: 7,
  },
  {
    word: "transparency",
    definition: "operating in an open way without secrets; clarity and accessibility",
    pronunciation: "/trænsˈpærənsi/",
    exampleSentence: "Greater transparency in government decision-making helps build public trust.",
    synonyms: ["openness", "accountability", "clarity"],
    topic: "Media",
    band: 7,
  },

  // === URBANISATION ===
  {
    word: "congestion",
    definition: "the condition of being overcrowded or overfull; traffic blockage",
    pronunciation: "/kənˈdʒɛstʃən/",
    exampleSentence: "Traffic congestion in major cities costs billions of dollars in lost productivity each year.",
    synonyms: ["overcrowding", "gridlock", "bottleneck"],
    topic: "Urbanisation",
    band: 6,
  },
  {
    word: "infrastructure",
    definition: "the basic physical systems of a country or region, such as transport and utilities",
    pronunciation: "/ˈɪnfrəˌstrʌktʃər/",
    exampleSentence: "Many developing cities lack the infrastructure to accommodate rapid population growth.",
    synonyms: ["facilities", "systems", "framework"],
    topic: "Urbanisation",
    band: 6,
  },
  {
    word: "gentrification",
    definition: "the process of renovating a district to conform to middle-class taste",
    pronunciation: "/ˌdʒɛntrɪfɪˈkeɪʃn/",
    exampleSentence: "Gentrification has revitalised some inner-city areas but has also displaced low-income residents.",
    synonyms: ["urban renewal", "regeneration", "revitalisation"],
    topic: "Urbanisation",
    band: 8,
  },
  {
    word: "migration",
    definition: "movement of people to a new area or country in order to find work or better living conditions",
    pronunciation: "/maɪˈɡreɪʃn/",
    exampleSentence: "Rural-to-urban migration is putting pressure on city services and housing in many nations.",
    synonyms: ["movement", "relocation", "displacement"],
    topic: "Urbanisation",
    band: 6,
  },
  {
    word: "metropolitan",
    definition: "relating to a large, densely populated urban area",
    pronunciation: "/ˌmɛtrəˈpɒlɪtən/",
    exampleSentence: "Metropolitan areas generate the majority of a country's economic output.",
    synonyms: ["urban", "city", "cosmopolitan"],
    topic: "Urbanisation",
    band: 7,
  },

  // === HIGH-FREQUENCY ACADEMIC WORDS ===
  {
    word: "significant",
    definition: "sufficiently great or important to be worthy of attention",
    pronunciation: "/sɪɡˈnɪfɪkənt/",
    exampleSentence: "There has been a significant increase in the number of students pursuing higher education.",
    synonyms: ["considerable", "substantial", "notable"],
    topic: "Education",
    band: 6,
  },
  {
    word: "consequently",
    definition: "as a result; therefore",
    pronunciation: "/ˈkɒnsɪkwəntli/",
    exampleSentence: "More people are working from home; consequently, demand for office space has declined.",
    synonyms: ["therefore", "thus", "as a result"],
    topic: "Society",
    band: 6,
  },
  {
    word: "exacerbate",
    definition: "make (a problem) worse",
    pronunciation: "/ɪɡˈzæsəbeɪt/",
    exampleSentence: "Poverty can exacerbate mental health issues, creating a damaging cycle of deprivation.",
    synonyms: ["worsen", "aggravate", "intensify"],
    topic: "Society",
    band: 8,
  },
  {
    word: "fundamental",
    definition: "forming a necessary base or core; of central importance",
    pronunciation: "/ˌfʌndəˈmɛntl/",
    exampleSentence: "Access to clean water is a fundamental human right that must be guaranteed globally.",
    synonyms: ["basic", "essential", "core"],
    topic: "Society",
    band: 6,
  },
  {
    word: "prevalent",
    definition: "widespread in a particular area at a particular time",
    pronunciation: "/ˈprɛvələnt/",
    exampleSentence: "Anxiety disorders are increasingly prevalent among adolescents in modern societies.",
    synonyms: ["widespread", "common", "rife"],
    topic: "Health",
    band: 7,
  },
  {
    word: "substantial",
    definition: "of considerable importance, size, or worth",
    pronunciation: "/səbˈstænʃl/",
    exampleSentence: "Governments need to make substantial investments in public transport to reduce car dependency.",
    synonyms: ["considerable", "significant", "sizeable"],
    topic: "Economy",
    band: 6,
  },
  {
    word: "inevitable",
    definition: "certain to happen; unavoidable",
    pronunciation: "/ɪnˈɛvɪtəbl/",
    exampleSentence: "Technological disruption of traditional industries seems inevitable in the modern era.",
    synonyms: ["unavoidable", "inescapable", "certain"],
    topic: "Technology",
    band: 7,
  },
  {
    word: "controversial",
    definition: "giving rise to public disagreement and debate",
    pronunciation: "/ˌkɒntrəˈvɜːʃl/",
    exampleSentence: "Capital punishment remains a highly controversial topic in many societies.",
    synonyms: ["contentious", "debatable", "disputed"],
    topic: "Society",
    band: 6,
  },
  {
    word: "facilitate",
    definition: "make an action or process easier or more achievable",
    pronunciation: "/fəˈsɪlɪteɪt/",
    exampleSentence: "Online platforms facilitate the exchange of knowledge between researchers worldwide.",
    synonyms: ["enable", "assist", "promote"],
    topic: "Technology",
    band: 7,
  },
  {
    word: "detrimental",
    definition: "tending to cause harm",
    pronunciation: "/ˌdɛtrɪˈmɛntl/",
    exampleSentence: "Excessive screen time can be detrimental to children's social and cognitive development.",
    synonyms: ["harmful", "damaging", "injurious"],
    topic: "Health",
    band: 7,
  },
  {
    word: "alleviate",
    definition: "make (suffering, deficiency, or a problem) less severe",
    pronunciation: "/əˈliːvieɪt/",
    exampleSentence: "Foreign aid programmes aim to alleviate poverty in the world's least developed countries.",
    synonyms: ["ease", "relieve", "reduce"],
    topic: "Society",
    band: 7,
  },
  {
    word: "incorporate",
    definition: "take in or include as part of a whole",
    pronunciation: "/ɪnˈkɔːpəreɪt/",
    exampleSentence: "Schools should incorporate critical thinking skills into the core curriculum.",
    synonyms: ["include", "integrate", "embed"],
    topic: "Education",
    band: 7,
  },
  {
    word: "phenomenon",
    definition: "a fact or situation that is observed to exist or happen",
    pronunciation: "/fɪˈnɒmɪnən/",
    exampleSentence: "The rise of remote working is a global phenomenon accelerated by the pandemic.",
    synonyms: ["occurrence", "event", "development"],
    topic: "Society",
    band: 7,
  },
  {
    word: "advocate",
    definition: "publicly recommend or support a cause or policy",
    pronunciation: "/ˈædvəkeɪt/",
    exampleSentence: "Many environmentalists advocate for a complete transition to renewable energy by 2050.",
    synonyms: ["support", "champion", "promote"],
    topic: "Environment",
    band: 7,
  },
  {
    word: "implement",
    definition: "put a plan or decision into effect",
    pronunciation: "/ˈɪmplɪmɛnt/",
    exampleSentence: "Governments must implement strict regulations to curb corporate pollution.",
    synonyms: ["apply", "execute", "enforce"],
    topic: "Society",
    band: 6,
  },
  {
    word: "comprehensive",
    definition: "complete and including everything that is necessary",
    pronunciation: "/ˌkɒmprɪˈhɛnsɪv/",
    exampleSentence: "A comprehensive healthcare system should be accessible to all citizens regardless of income.",
    synonyms: ["thorough", "extensive", "complete"],
    topic: "Health",
    band: 6,
  },
  {
    word: "disproportionate",
    definition: "too large or too small in comparison with something else",
    pronunciation: "/ˌdɪsprəˈpɔːʃənɪt/",
    exampleSentence: "The poorest communities bear a disproportionate burden of environmental pollution.",
    synonyms: ["unequal", "excessive", "lopsided"],
    topic: "Environment",
    band: 8,
  },
  {
    word: "sophisticated",
    definition: "having a refined understanding of complex issues; technically advanced",
    pronunciation: "/səˈfɪstɪkeɪtɪd/",
    exampleSentence: "Sophisticated data analysis tools allow scientists to identify patterns in vast datasets.",
    synonyms: ["advanced", "complex", "refined"],
    topic: "Technology",
    band: 7,
  },
  {
    word: "diminish",
    definition: "make or become less",
    pronunciation: "/dɪˈmɪnɪʃ/",
    exampleSentence: "Overuse of antibiotics has caused their effectiveness to diminish significantly.",
    synonyms: ["reduce", "decrease", "lessen"],
    topic: "Health",
    band: 7,
  },
  {
    word: "paramount",
    definition: "more important than anything else; supreme",
    pronunciation: "/ˈpærəmaʊnt/",
    exampleSentence: "The safety of patients must be paramount in any healthcare system.",
    synonyms: ["supreme", "chief", "most important"],
    topic: "Health",
    band: 8,
  },
]

// Get a random word for the day (deterministic based on date)
export function getDailyWord(date: string): WordEntry {
  const dateNum = date.replace(/-/g, "").slice(-4)
  const index = parseInt(dateNum, 10) % WORD_BANK.length
  return WORD_BANK[index]
}

// Get words by topic
export function getWordsByTopic(topic: string): WordEntry[] {
  return WORD_BANK.filter((w) => w.topic === topic)
}

// Get words by band
export function getWordsByBand(band: number): WordEntry[] {
  return WORD_BANK.filter((w) => w.band >= band)
}
